### ISSUE TITLE
Is native supported?

### ISSUE THREAD

**Issue by puks** [floatinghotpot/cordova-plugin-facebookads#11]
Is native supported? I see a sample of a native ad on the readme but i cant make it to work.

**Comment by floatinghotpot** [comment]
native ad is supported, see the demo code:
https://github.com/floatinghotpot/cordova-plugin-facebookads/blob/master/test/index.html

Or, quickly verify the plugin with its demo on emulator:
```bash
[sudo] npm install -g plugin-verify
plugin-verify cordova-plugin-facebookads
```
