### ISSUE TITLE
error when install plugin by plugman

### ISSUE THREAD

**Issue by y2x33** [floatinghotpot/cordova-plugin-facebookads#12]
![image](https://cloud.githubusercontent.com/assets/11724193/8648853/f648132a-2996-11e5-9029-30552d68dcf5.png)

I can install successfully by "cordova plugin"command,but I failed to install it by plugman.WHY?
Thank you for help~

**Comment by y2x33** [comment]
PS: I also find I cannot get the ads successfully in the demo provided.There's an error 2001 & 1000.

**Comment by floatinghotpot** [comment]
If you are in China, access to Facebook will fail due to GFW (you know it, right?)

AdMob is more recommended, as Google has many partners and the Ad fill rate is very high (> 95%)

See:
https://github.com/floatinghotpot/cordova-admob-pro

**Comment by y2x33** [comment]
Thank you. I guess so.
And I will try admob ^_^.

**Comment by y2x33** [comment]
I have used vpn to solve the internet problem（and I can successfully visit google, youtube and so on）, but both two errors still exist when I run the demo on my device（and I ever ran it successfully on this device）. I wonder whether there is something new in audience network and the plugin goes wrong？
THX again!
