### ISSUE TITLE
2000 server error

### ISSUE THREAD

**Issue by manuelpaulo** [floatinghotpot/cordova-plugin-facebookads#13]
Using your own example code and only that, I get:
```
2015-08-01 04:15:30.337 MyApp[27775:223365] [FBAudienceNetworkLog/FBAdProvider:137 <error>] Ad request error: Error Domain=com.facebook.ads.sdk Code=2000 "Server Error" UserInfo=0x7feced9940d0 {NSLocalizedDescription=Server Error, FBAdErrorDetailKey={
    url = "https://graph.facebook.com/network_ads_common/";
}}
2015-08-01 04:15:30.337 MyApp[27775:223365] FacebookAds, onAdFailLoad, {'adNetwork':'FacebookAds','adType':'banner','adEvent':'onAdFailLoad','error':2000,'reason':'Server Error'}
```
Notes: Clean project with only your plugin and your example code, tested on simulator and real device, internet connection is fine. I am in the EU and have no firewalls, government limitations or ad blocks.

**Comment by floatinghotpot** [comment]
Pleas change the app id to your own.

**Comment by manuelpaulo** [comment]
Already did that, previously to testing your own example. Same problem... :(

**Comment by floatinghotpot** [comment]
Did you get your app id approved in Facebook audience network?

**Comment by manuelpaulo** [comment]
You are absolutely right. First when I copy paste my App id, I missed one char and got the 2000 server error message. Then, I tried a clean app with your code only and got the same message.

What should be fixed, imho. 

You, or Facebook should not return an undocumented error code when app id is wrong. https://developers.facebook.com/docs/marketing-api/error-reference

You should remove the app ids on your exemple code, since as is, the code is not working
https://github.com/floatinghotpot/cordova-plugin-facebookads/blob/master/test/index.html

Last, but not least, thanks for helping so much the community. Also, since there is no longer a free version, how are being paid now for your work? Still the 3% add cut only?

**Comment by floatinghotpot** [comment]
The app id in index.html is for demo purpose only, and may not work any more, you have to replace it with your own app id.

It's up to you to choose one of the options, either no need to spend a cent but share 2% ad traffic, or pay $20 for a license to disable the ad traffic, see: http://rjfun.github.io/

**Comment by manuelpaulo** [comment]
Thanks!
