### ISSUE TITLE
(#606) Application is rejected

### ISSUE THREAD

**Issue by manuelpaulo** [floatinghotpot/cordova-plugin-facebookads#16]
I am getting this on Android.

```E/FacebookAdsSDK﹕ Facebook Ads SDK req failed 4166ms {
    "error": {
    "message": "(#606) Application is rejected",
    "type": "OAuthException",
    "code": 606
    }
    } org.apache.http.client.HttpResponseException: Bad Request
08-05 06:55:35.781  12912-13025 D/FacebookAdsSDK﹕ Error code [1000] Bad Request```

With my correct test device hashtag and an app id I already use on iOS with no issues.
Build a clean project with only your plugin and your demo code, with ids changed to mine.

Thanks for any support.

**Comment by floatinghotpot** [comment]
The possible reason might be: the plugin will failover to demo app id when it failed loading ad resource with your app id. But unfortunately, the demo app id itself is no longer valid, according to feedback from Facebook team.

**Comment by manuelpaulo** [comment]
Thanks for the reply. But why would it fail loading ad resource with your app id from Android and not from iOS? Should I get in touch with FB? Your code works with other app ids?

**Comment by manuelpaulo** [comment]
Could it be the Android debug key hash?

**Comment by manuelpaulo** [comment]
Well, to sum up, 

1. I've build a new app using only your code (plugin and demo) and the latest cordova.
2. The only thing needed from my side was the device hashtag and the app id. The hashtag is correct and the app id is the same I use on the iOS version.

Thus, I must conclude there's something wrong with your code. My Java knowledge is very limited but I will now try to dig in your code to see if I can find anything.

**Comment by manuelpaulo** [comment]
You are correct. Fixing it is very easy. I went to FacebookAdPlugin.java and changed your id with mine and now it works. Yes, I know, we are not supposed to do this.... 

You need to get in touch with FB urgently and fix this issue asap as you deserve the 3% ad share for the hard work on this plugin.
