### ISSUE TITLE
Can't scroll the webview when touching on the native ad

### ISSUE THREAD

**Issue by IronLung7** [floatinghotpot/cordova-plugin-facebookads#17]
The native ad view is upper on the webview, how can make scroll work well?

**Comment by floatinghotpot** [comment]
yes, it's a known issue but not fixed yet.

**Comment by RashadPark** [comment]
:( we are waiting for fix

**Comment by IronLung7** [comment]
Bring the webView to the front, then select and pass motionEvent from webView to the layout which contains ad view.  will fix this

**Comment by RashadPark** [comment]
@IronLung7 i am using it PGB. 
What i'm doing is - user clicks on button show more and via ajax i load the content and native ad - after that i call nativeadclickarea - top of native ad is non clickable, only the bottom of native ad till down is clickable, and thats why users cant scroll or clik to anything. Thanks

**Comment by floatinghotpot** [comment]
Both android & ios fixed in cordova-plugin-facebookads v4.7.3

**Comment by JRCuellar** [comment]
Hi, 

I updated to version 4.22.2 and I can't scroll when touching on the native ad. Are you sure that is working ok?

I've this problem only when I do scroll inside native ad. When I touch outside native ad all is ok. 

Can you test it? Thanks for your help
