### ISSUE TITLE
update ios sdk to v4.6.0 to support ios 9

### ISSUE THREAD

**Issue by Bnaya** [floatinghotpot/cordova-plugin-facebookads#21]
By facebook docs, its required to update the sdk to  v4.6.0 in order to build the app for ios 9
https://developers.facebook.com/docs/audience-network/ios9 

The docs also tell to add some entries to the  plist, the plugin should do that too (?)

**Comment by floatinghotpot** [comment]
The SDK is updated to v4.7.0, please enjoy.

As to the "NSAppTransportSecurity" issue, it's handled already.

**Comment by Bnaya** [comment]
Thanks!
