### ISSUE TITLE
Support for window phone?

### ISSUE THREAD

**Issue by Divyaadz** [floatinghotpot/cordova-plugin-facebookads#38]
Whether this plugin with support for window phone? If not what is the best option plugin for windows 8.1 OS ads

**Comment by floatinghotpot** [comment]
No, as only iOS & android SDK from Facebook.

Now only Google provide AdMob SDK for iOS / android and windows phone, so you can try `cordova-plugin-admobpro`, see it here: https://github.com/floatinghotpot/cordova-admob-pro
