### ISSUE TITLE
onclick event

### ISSUE THREAD

**Issue by halkoy** [floatinghotpot/cordova-plugin-facebookads#46]
How to use onclick event for this facebookads plugin? I want to learn that user click the ad or not? I can not find pls help..

**Comment by floatinghotpot** [comment]
Instead of listen to onclick event, please listen to ad event:
```javascript
document.addEventListener('onAdLeaveApp', function(data) {
});
```

See more example code here:
https://github.com/floatinghotpot/cordova-plugin-facebookads/blob/master/test/index.html

**Comment by halkoy** [comment]
thank you so much...
