### ISSUE TITLE
FacebookAds is not defined

### ISSUE THREAD

**Issue by Lafaa** [floatinghotpot/cordova-plugin-facebookads#47]
Hi everyone, 
I just tried to add this plugin for my ionic 2 app, but i can't find a way to let it work. 
I added the plugin via prompt, then wrote down: 

```
if(FacebookAds) FacebookAds.createBanner( {
      adId: "AAAAAAAAA_AAAAAAAAA",  //my id
      position:FacebookAds.AD_POSITION.BOTTOM_CENTER, 
      autoShow:true} );
```

But Visual Code gives me error on FacebookAds cause it doesn't know where to find it. Do i have to import it from somewhere?  

Thanks for your help!

**Comment by technotip** [comment]
Declare variable FacebookAds at the top of the component page.

You can see it here [Facebook Banner and Interstitial Ads: Ionic 2](http://technotip.com/5123/facebook-banner-and-interstitial-ads-ionic-2/)

**Comment by seomaz** [comment]
`declare var FacebookAds: any;` in app.component.ts not work for me ionic 3
error: FacebookAds is not defined

**Comment by hiionic** [comment]
I have the same problem.

declare var FacebookAds: any; in app.component.ts not work for me ionic 3
 error: FacebookAds is not defined

**Comment by IvanLencina** [comment]
Same problem here. Declaring FacebookAds not working.

Solved with this [fork](https://github.com/ElieSauveterre/cordova-plugin-facebookads)

**Comment by IvanLencina** [comment]
@technotip Where we find the id to use in `FacebookAds.createNativeAd('123213123123')`?  I can't find an option to create an ad in my developer account.

**Comment by fvdavid** [comment]
@IvanLencina 👍

**Comment by astechnolabs-fullstack** [comment]
> Same problem here. Declaring FacebookAds not working.
> 
> Solved with this [fork](https://github.com/ElieSauveterre/cordova-plugin-facebookads)

  Same issue here, but I am Not understanding your answer, Please write sample code of that line.
