### ISSUE TITLE
Ionic 2 Implementation Document

### ISSUE THREAD

**Issue by technotip** [floatinghotpot/cordova-plugin-facebookads#48]
Can you please provide documentation to implement FacebookAds plugin in Ionic 2?

Also please post more documentation of 'Native Ads'. We want to know the positioning of the native ad links - setNativeAdClickArea() This is confusing.

**Comment by sonoftheweb** [comment]
I too would like to know how this is done in Ionic 2.

**Comment by technotip** [comment]
I could implement Banner Ads and Interstitial Ads [Facebook Banner and Interstitial Ads: Ionic 2](http://technotip.com/5123/facebook-banner-and-interstitial-ads-ionic-2/)
And half-way through Native Ads [Facebook Native Ads: Ionic 2](http://technotip.com/5128/facebook-native-ads-ionic-2/)

**Comment by floatinghotpot** [comment]
Thanks to @technotip, nice job!
