### ISSUE TITLE
iOS and Android SDK updates

### ISSUE THREAD

**Issue by butlimous** [floatinghotpot/cordova-plugin-facebookads#5]
Hey Raymond :)

There have been several updates for the Audience SDK for both android and ios.
 Current Android: 3.23.0
 Current iOS: 3.23.1

Will you update soon to avoid any bugs? as there are many that have been fixed in these updated

Thanks
Regards
Michael

**Comment by floatinghotpot** [comment]
Michael, thanks for reminder. Will find time to update the plugin.

**Comment by floatinghotpot** [comment]
Done.
