### ISSUE TITLE
NSPhotoLibraryUsageDescription key? For phonegap build.

### ISSUE THREAD

**Issue by wizajay** [floatinghotpot/cordova-plugin-facebookads#50]
I have successfully implemented the native ad code for Android using phonegap build. But for ios I am getting my binary rejected due to this missing plist key. Help please, on how to declare it on config.xml

**Comment by floatinghotpot** [comment]
I don't think the plugin or Facebook AudNet SDK will access user's photo library.

BTW, to declare a usage in plist, simply modify your app-Info.plist or in Xcode project.

**Comment by juxfr** [comment]
You can declare it like this:
<config-file platform="ios" parent="NSPhotoLibraryUsageDescription" mode="replace">  
      <string>Your text...</string> 
  </config-file>

**Comment by wizajay** [comment]
@juxfr Thank you
