### ISSUE TITLE
FacebookAds is not defined - Ionic 1.4.0

### ISSUE THREAD

**Issue by anmolarora1** [floatinghotpot/cordova-plugin-facebookads#51]
I'm following the code from your example 'index.html' but it doesn't seem to be working at all because 'FacebookAds' is not defined. So every time, I'm getting this message -FacebookAds plugin not ready.

**Comment by floatinghotpot** [comment]
in the demo index.html, `FacebookAds` means `window.FacebookAds`.

In Ionic, maybe it should be refered as `$window.FacebookAds`?

**Comment by anmolarora1** [comment]
Thanks. It works with window.FacebookAds.
But I'm still not able to create any ads using window.FacebookAds.createBanner() and there's not even any error message for that. Is there any way to log error messages/response from these methods?

**Comment by anmolarora1** [comment]
I'm getting error '1203' with error data as 'fatal'. It seems that you haven't added a description for that in your [FAQs](https://github.com/floatinghotpot/cordova-plugin-facebookads/wiki/FAQ) . So can you please help?

**Comment by Vivek-abstract** [comment]
I'm facing the same issue in my ionic app
