### ISSUE TITLE
Ionic. Server Error. Code=2000.

### ISSUE THREAD

**Issue by sergey-prikhno** [floatinghotpot/cordova-plugin-facebookads#54]
Hello! I'm developing a mobile application on Ionic 1(iOS, Android) and I can not use this plugin in the application.
In the x-code logs, I have an error:

> [FBAudienceNetworkLog/FBAdProvider:138 ] Ad request error: Error Domain=com.facebook.ads.sdk Code=2000 "Server Error" UserInfo=0x1b3aae80 {FBAdErrorDetailKey={
code = "-1";
message = Fatal;
type = OAuthException;
url = "https://graph.facebook.com/network_ads_common/";
}, NSLocalizedDescription=Server Error}
FacebookAds, onAdFailLoad, {'adNetwork':'FacebookAds','adType':'native','adEvent':'onAdFailLoad','error':2000,'reason':'Server Error'}

Am I right to understand that this error is due to the not-updated Facebook Audience Network SDK? Do you still support your plugin? If so, when can you update it?

P.S. I tried the solutions that are discussed here, but I did not get to use this plugin.

**Comment by Slavezax** [comment]
#55 

I think we are having the same problem.

**Comment by floatinghotpot** [comment]
Hi guys, the FB AudNet SDK has been upgrade to latest v4.22.1, and the plugin has also been updated to match the new SDK.

Now it's fixed and published to npm as: 
`cordova-facebook-audnet-sdk@4.22.1`
`cordova-plugin-facebookads@4.22.1`

**Comment by luizsouzaqualinfo** [comment]
Hi, I'm having the same problem in the iOS app. In Android the Ad appears normally, but in iOS it gives this error, I am using version 4.23.2 of cordova-plugin-facebookads. I'm using a placement id for Android and another Placement Id for iOS

**Comment by W1ldW1ngs** [comment]
We are getting this same error when trying to get iOS to load ads.

**Comment by floatinghotpot** [comment]
We will look into this issue.

**Comment by chrishenx** [comment]
@floatinghotpot Is there any advance on the issue? I'm having this error with version 4.23.2 as @luizsouzaqualinfo 

<img width="548" alt="captura de pantalla 2017-09-29 a la s 18 34 08" src="https://user-images.githubusercontent.com/6645155/31039649-d995769c-a544-11e7-9298-551fb8c9ca80.png">

Android works fine, but the iOS version seems to be broken.

**Comment by floatinghotpot** [comment]
Please update the plugin to latest version. 

When type `cordova plugin ls`, you should see:
```
cordova-facebook-audnet-sdk 4.26.2 "Facebook AudienceNetwork SDK for Cordova"
cordova-plugin-extension 1.5.2 "Cordova Plugin Extension"
cordova-plugin-facebookads 4.23.2 "FacebookAds"
```

If not, remove the plugin and add back again.
```bash
cordova plugin rm cordova-plugin-facebookads
cordova plugin rm cordova-facebook-audnet-sdk

cordova plugin add cordova-plugin-facebookads
```

**Comment by chrishenx** [comment]
@floatinghotpot Yeap, I have that same output as you pointed out.

**Comment by floatinghotpot** [comment]
Please read #77, same issue. Let's discuss it in that tracker.
