### ISSUE TITLE
facebook audience networkd new sdk

### ISSUE THREAD

**Issue by halkoy** [floatinghotpot/cordova-plugin-facebookads#56]
hello,
I integrate it with my app but not showing evet test ads, I think sdk is old.
would you update the sdk please ? or how can we do it manually

thnx

**Comment by jonas-m-** [comment]
You can do it manually, please see this pull request: https://github.com/floatinghotpot/cordova-plugin-facebookads/pull/53

**Comment by Slavezax** [comment]
When I change the AudienceNetwork jar with the latest one, this doesn't build with error:

:compileArmv7DebugJavaWithJavac
/Users/B42/Bilemezsin/platforms/android/src/com/rjfun/cordova/facebookads/FacebookAdPlugin.java:211: error: <anonymous com.rjfun.cordova.facebookads.FacebookAdPlugin$1$2> is not abstract and does not override abstract method onLoggingImpression(Ad) in AdListener

        	unit.ad.setAdListener(new AdListener(){
        	                                      ^
/Users/B42/Bilemezsin/platforms/android/src/com/rjfun/cordova/facebookads/FacebookAdPlugin.java:383: error: <anonymous com.rjfun.cordova.facebookads.FacebookAdPlugin$4> is not abstract and does not override abstract method onLoggingImpression(Ad) in AdListener

    ad.setAdListener(new AdListener(){

                                     ^
/Users/B42/Bilemezsin/platforms/android/src/com/rjfun/cordova/facebookads/FacebookAdPlugin.java:459: error: <anonymous com.rjfun.cordova.facebookads.FacebookAdPlugin$5> is not abstract and does not override abstract method onLoggingImpression(Ad) in AdListener

    ad.setAdListener(new InterstitialAdListener(){

**Comment by floatinghotpot** [comment]
It's fixed and see it in #55
