### ISSUE TITLE
FacebookAds is not defined

### ISSUE THREAD

**Issue by Slavezax** [floatinghotpot/cordova-plugin-facebookads#57]
[INFO:CONSOLE(519)] "Uncaught ReferenceError: FacebookAds is not defined", source: file:///android_asset/www/hesabim.html (519) 

I'm getting this error from console when I'm trying on Android.

What could be the reason? I even tried alternatife forks but still the same error.

I'm on Phonegap CLI.

**Comment by SidMehta** [comment]
You should call the API after "ondeviceready" event. That will most likely solve this problem.

**Comment by floatinghotpot** [comment]
Hi guys, the FB AudNet SDK has been upgrade to latest v4.22.1, and the plugin has also been updated to match the new SDK.

Now it's fixed and published to npm as: 
`cordova-facebook-audnet-sdk@4.22.1`
`cordova-plugin-facebookads@4.22.1`
