### ISSUE TITLE
1203 error not displaying ad

### ISSUE THREAD

**Issue by halkoy** [floatinghotpot/cordova-plugin-facebookads#58]
hello,
I have installed the latest version of plugin. I use Intel XDK to build. There is no problem for the build and while using test mode interstitial ad is displaying.
But If I turn to test mode to real mode, facebook audience network returns success but ad is not displaying and I got this error for the onload of ad event
"1203 / initial request from a bundle must come from a App Admin Developer or Tester."

This app is new and new bundle but I am the admin of the app in the roles. Also I login to facebook app with the admin user of app.
Do you have any idea how to pass this error ?

thnx

**Comment by SidMehta** [comment]
@halkoy I am able to see the test ads. But live ads are always returning 1001 : No Fill. These used to work for the previous sdk versions. I also have the app admin logged in the Facebook android app. Mine is also a new bundle. Will update you if I am able to resolve this somehow.

**Comment by halkoy** [comment]
anyone have idea ? I can see the test ads but when change to real ads I got this error.
"1203 / initial request from a bundle must come from a App Admin Developer or Tester."

**Comment by halkoy** [comment]
anyone have idea ? I can see the test ads but when change to real ads I got this error.
"1203 / initial request from a bundle must come from a App Admin Developer or Tester."

**Comment by halkoy** [comment]
..
