### ISSUE TITLE
PhoneGap build fails for iOS (Android OK)

### ISSUE THREAD

**Issue by blukis** [floatinghotpot/cordova-plugin-facebookads#59]
Build fails on PhoneGap build for iOS with these parameters:
```
<preference name="phonegap-version" value="cli-6.5.0" />
<plugin name="cordova-plugin-facebookads" version="4.22.2"/>
```
Android build works OK.   I can provide a more complete config.xml, or build log output if that would be helpful.

**Comment by floatinghotpot** [comment]
We need more details, please show me the build log.

**Comment by blukis** [comment]
PhoneGap build log, and example failing zip file (upload this .zip to PhoneGap build to replicate failure) attached.  Thanks!

[www.zip](https://github.com/floatinghotpot/cordova-plugin-facebookads/files/1023774/www.zip)
[build_log.txt](https://github.com/floatinghotpot/cordova-plugin-facebookads/files/1023775/build_log.txt)

**Comment by juxfr** [comment]
I've got the same problem.

**Comment by halkoy** [comment]
phonegap ios does not build for this plugin. pls help

**Comment by halkoy** [comment]
@floatinghotpot pls help us for phonegap IOS build error. We need it so much

**Comment by floatinghotpot** [comment]
I've just upgraded facebook SDK to v4.23.0, please try the new version.

**Comment by juxfr** [comment]
It seems to work again on my side.
Build is OK and Facebook ads work.

**Comment by blukis** [comment]
Working now, thanks!
