### ISSUE TITLE
Hashed device ID

### ISSUE THREAD

**Issue by butlimous** [floatinghotpot/cordova-plugin-facebookads#6]
Hey Raymond :)

In your doc, you state that in order to test and ad unit on a device, we should get the hashed device id and use it in the deviceHash parameter. From where can I get that?

Thanks
Regards
Michael

**Comment by butlimous** [comment]
Does it get printed in the console.log or what? Do I have to do anything to get it logged?

**Comment by floatinghotpot** [comment]
No, you cannot see it with console.log, if build and run with Xcode or Eclipse, you can see the device ID in log view.
