### ISSUE TITLE
getting 2000 : Server Error on ios (iphone, simulator)

### ISSUE THREAD

**Issue by binita12345** [floatinghotpot/cordova-plugin-facebookads#60]
i have using following code in my app.js,

    var FacebookAds;
    var ad_units = {
            ios : { 
              banner:"177243545465757756776867680276",
              interstitial:"177243545465757756776867680277",
                  nativeAd:"177243545465757756776867680278"
            },
            android : {
              banner:"177243545465757756776867680276",
              interstitial:"177243545465757756776867680277",
                  nativeAd:"177243545465757756776867680278"
            }
          };
    var adid = (/(android)/i.test(navigator.userAgent)) ? ad_units.android : ad_units.ios;
    if(window.FacebookAds) {
            window.FacebookAds.createBanner({
              adId: adid.banner,
              position: window.FacebookAds.AD_POSITION.TOP_CENTER,
              deviceHash: '731421801592e1c71987230e5fbc062689a59c27',
              // isTesting: false, // receiving test ad
              autoShow: true,
              overlap: true
              });
            window.FacebookAds.showBanner();
          }

i got this error:

    2017-05-24 10:16:01.953 myApp[1640:51078] FacebookAds, onAdFailLoad, {'adNetwork':'FacebookAds','adType':'banner','adEvent':'onAdFailLoad','error':2000,'reason':'Server Error'}

Above code is working fine for android, but not only for ios.
Please give me any solution as soon as possible.

**Comment by diegorene** [comment]
Hello, 
Did you found any solution for this problem? I also updated the sdk and it not woks on ios, android its working fine.


Thanks

**Comment by floatinghotpot** [comment]
I've just upgrade the facebook SDK to v4.23.0, please try the new version.

**Comment by floatinghotpot** [comment]
Fixed, See also: #59
