### ISSUE TITLE
FacebookAds.createBanner success callback even when failed?

### ISSUE THREAD

**Issue by blukis** [floatinghotpot/cordova-plugin-facebookads#61]
When I put my phone (Android) into airplane mode before opening my app, the FacebookAds.createBanner() executes a "success" callback with "OK" as parameter value, and no ad displays.  Shouldn't the "fail" callback be executed in this case?  How can I detect whether or not ad successfully displayed?

(It's possible I'm misunderstanding the intention of success/fail here.)  Thanks!

My more complete call looks like this...
```
FacebookAds.createBanner({
	adId: fb_placementID,
	position:FacebookAds.AD_POSITION.TOP_CENTER, 
	autoShow:true
}, function(someObj) { //fb-success
	alert("fb-success: " + JSON.stringify(someObj));
}, function(someObj) { // fb-fail
	alert("fb-fail: " + JSON.stringify(someObj));
});

// Results in alert [fb-success: "OK"] whether or not ad actually displays.
```

Update: I see the same "OK"/but-no-ad behavior when I (temporarily) disable my ad placement in Facebook audience network admin area.  I would again expect the fail callback to execute in this case, but success is called instead.

**Comment by floatinghotpot** [comment]
Please listen to event 'onAdLoaded' instead of using createBanner callback. Cause it will take some time to load Ad resource from server.
```javascript
document.addEventListener('onAdLoaded', function(data){
});
document.addEventListener('onAdFailLoad', function(data){
});
```

**Comment by blukis** [comment]
Great, thanks!  For future confused developers like me, might these supported events be documented somewhere in the readme?

**Comment by floatinghotpot** [comment]
Yes, your advice is very good. And, what you originally expect from instinct is also very reasonable.

We will improve the API and make it easier to use.

BTW, for the current version, here are some example code, FYI:
https://github.com/floatinghotpot/cordova-plugin-facebookads/blob/master/test/index.html
