### ISSUE TITLE
iOS statusbar overlays banner ad

### ISSUE THREAD

**Issue by blukis** [floatinghotpot/cordova-plugin-facebookads#64]
On iOS, FB ad overlaps (top) statusbar with position: FacebookAds.AD_POSITION.TOP_CENTER.  (i.e. the status bar text & icons are appearing over top some of the ad content.)

It's the same whether or not I set the webview to overlap statusbar through cordova-plugin-statusbar plugin [https://www.npmjs.com/package/cordova-plugin-statusbar].

It seems on Android (using same postion: FacebookAds.AD_POSITION.TOP_CENTER), FB ad shows just below the status bar, not overlapping.

Is this iOS/Android difference by design? or am I maybe doing something wrong?  (As a side note, the iOS statusbar/ad overlapping behavior I'm seeing is probably never desired, and probably violates some FB audience network term or other.)

**Comment by floatinghotpot** [comment]
If you want to avoid status bar overlap the ad, try add one more option `offsetTopBar:true` when create the banner.
