### ISSUE TITLE
Facebook required implementation upgrades

### ISSUE THREAD

**Issue by princekero** [floatinghotpot/cordova-plugin-facebookads#66]
Since Facebook announced Required Implementation Upgrades and give the deadline on November 1st. 
https://www.facebook.com/audiencenetwork/news-and-insights/required-changes-for-audience-network-publishers

Is this plugin fine with these requirements?
such as cache ads for 60 minutes or less...

**Comment by floatinghotpot** [comment]
this plugin has been upgraded to Facebook SDK v4.23.0. 

Please update, by removing the plugin and add again.
```bash
cordova plugin rm cordova-plugin-facebookads
cordova plugin rm cordova-facebook-audnet-sdk

cordova plugin add cordova-plugin-facebookads
```
