### ISSUE TITLE
Native ads

### ISSUE THREAD

**Issue by manuelpaulo** [floatinghotpot/cordova-plugin-facebookads#7]
Hi,

Are you considering supporting the new native ads format? 

https://developers.facebook.com/docs/audience-network/ios/nativeadtemplate

Thanks a lot!

**Comment by floatinghotpot** [comment]
As my workload is quite high recently, it's not on my schedule yet, unless anyone treat it as an outsourcing project to meet their business needs.

**Comment by floatinghotpot** [comment]
This feature is added now.
