### ISSUE TITLE
Getting Server Error 2000 (iOS)

### ISSUE THREAD

**Issue by W1ldW1ngs** [floatinghotpot/cordova-plugin-facebookads#70]
We are running into Server Error 2000, when  trying to display native ads on iOS. Placement IDs match however looks like this has been an issue in the past.

https://github.com/floatinghotpot/cordova-plugin-facebookads/issues/60

Any thoughts on a fix for this @floatinghotpot?

**Comment by W1ldW1ngs** [comment]
This actually is resolved. It appears we were only receiving this error on an older test device.

**Comment by dhwalin** [comment]
Tried everything.. Each thread. But still it showing server error.
