### ISSUE TITLE
Paid for Pro support, got no reply and no refund

### ISSUE THREAD

**Issue by SafwanHak** [floatinghotpot/cordova-plugin-facebookads#73]
I have an issue with the code.  Due to time constraint, I've chosen to pay for support and emailed the author 3 times and finally opened a paypal dispute and still nothing. 

If the author cannot be bothered to respond to those who pay him, I wouldn't trust him to support these open libraries.

If you are able to use the plugin without trouble, good for you but avoid paying the author.

**Comment by floatinghotpot** [comment]
@SafwanHak , we are sorry to reply late, but when we send the license via email, we just got this response. Is there something wrong with your email service? See the screenshot below.

![2017-08-31 12 31 57](https://user-images.githubusercontent.com/2339512/29883791-e44967e2-8de3-11e7-915f-62fc605640c0.png)
