### ISSUE TITLE
native ad image not showing in test 

### ISSUE THREAD

**Issue by hodaifa82** [floatinghotpot/cordova-plugin-facebookads#75]
the image of the ad in test mode is not showing but the click area and the ad text is ok also banner and interstitial is showing the the image

**Comment by floatinghotpot** [comment]
Did you add this line into your html file?
```html
<meta 
http-equiv="Content-Security-Policy" 
content="default-src * gap://ready file:; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src * 'unsafe-inline' 'unsafe-eval'">
```

Not sure if you implemented it properly or not. Try using this demo file for a testing.
https://github.com/floatinghotpot/cordova-plugin-facebookads/blob/master/test/index.html

**Comment by hodaifa82** [comment]
@floatinghotpot  itry to use the file its not working , the banner working , the interstitial working , 
but the native worked only when the banner is there and i have to remove and create again ?????? else i have this image 

![screen shot 2017-09-10 at 10 03 10 am](https://user-images.githubusercontent.com/27774777/30246894-ee722f3a-9606-11e7-8e23-23e52da07810.png)
